tasks:
  - name: setup
    init: |
          docker-compose build
    command: | 
            docker-compose up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 8080
    onOpen: ignore
  - port: 6379
    onOpen: ignore

