version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-service
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"

  # Java Movie Service
  backend:
    image: movie-backend:latest
    container_name: backend
    depends_on:
      - redis
    links:
      - "redis:redis"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MOVIE_INSERT_ON_STARTUP=true
      - MOVIE_DATA_DIR=./
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  # React Frontend Service
  frontend:
    image: movie-frontend:latest
    container_name: movie-frontend
    depends_on:
      - backend
    links:
      - "backend:backend"
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_MOVIE_SERVICE_HOST=localhost
      - REACT_APP_MOVIE_SERVICE_PORT=8080
      - REACT_APP_API_KEY=8be8e5bc13a1edef7fd11cedcdce8a27
networks:
  default:
    name: redis-movie-network
